//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalAppointment.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DentistID { get; set; }
        public string PurposeDescription { get; set; }
        public string Status { get; set; }
    
        public virtual Dentist Dentist { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
