//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalAppointment.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSet
    {
        public int TimeId { get; set; }
        public string TimeName { get; set; }
        public string TimeDescription { get; set; }
    }
}
