//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalAppointment.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Appointments
    {
        public int AppointmentId { get; set; }
        public int PatientId { get; set; }
        public string Patient_Name { get; set; }
        public string AppointmentPurpose { get; set; }
        public string Email { get; set; }
        public string DateAndTime { get; set; }
        public string Status { get; set; }
    }
}
